### ISSUE TITLE
Search Bar is not in good place

### ISSUE THREAD

**Issue by AdithyaKrishnaK** [sugarlabs/www-sugarlabs#330] opened 2020-10-28 11:49 UTC
![image](https://user-images.githubusercontent.com/24326156/97431974-40765e80-1941-11eb-994c-758113f12f8e.png)

![image](https://user-images.githubusercontent.com/24326156/97432035-584de280-1941-11eb-981d-eaf947f137d1.png)

The first one is from Edge browser and the second from Chrome. There isn't enough space for search bar in nav bar.

**Comment by quozl** [comment] 2020-10-29 03:51
Thanks.  But this is effectively a duplicate of https://github.com/sugarlabs/www-sugarlabs/issues/305, so closing.

**Closed by quozl** 2020-10-29 03:51 UTC
