### ISSUE TITLE
Titles on footer don't contrast well with background color

### ISSUE THREAD

**Issue by khreate** [sugarlabs/www-sugarlabs#145] opened 2017-12-03 02:18 UTC
![readability](https://user-images.githubusercontent.com/26176077/33521649-c7649eae-d79d-11e7-8a9e-93a1bc846185.JPG)

As seen in the picture, the titles for "Sugar Labs", "Development", and "Resources" are difficult to read. Consider using a lighter color (a lighter grey, perhaps) to create more contrast, increasing readability.

**Comment by khreate** [comment] 2017-12-03 02:21
Also, when these labels are hovered over, the cursor becomes activated. Not sure if this was intentional as they are not linked to anything.

**Comment by pg07codes** [comment] 2018-07-09 04:23
i cant reproduce this issue. If it has been fixed, please close the issue.

**Comment by Pro-Panda** [comment] 2018-07-09 06:09
While the contrast has been fixed, the cursor still becomes activated. The issue has been partially fixed

**Comment by FiberesimaJoseph** [comment] 2020-04-09 14:50
Why not change the font color of the text i think the background is okay if the font colors are changed

**Closed** 2020-04-19 17:14 UTC
