### ISSUE TITLE
Need improvements

### ISSUE THREAD

**Issue by leonardokwan** [sugarlabs/www-sugarlabs#153] opened 2017-12-03 11:42 UTC
First, pls change the website appearances when we click the Try now button. At first i thought the websites crashed and just show a pure white screen with a name box. And pls make more ez to navigate around the website. Second, i suggest that we can do/access the search engine on the main page not on a new web page. Lastly, give more instruction and quick tips for new people how to use this websites feature.

**Comment by quozl** [comment] 2017-12-04 00:20
Exact duplicate of #152 from a different identity without any explanation, closing this one.

**Closed by quozl** 2017-12-04 00:20 UTC
